version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: smb
    ports: ['5432:5432']
  redis:
    image: redis:6
    ports: ['6379:6379']
